server:
  port: 18081

spring:
  datasource:
    url: ${USER_DATASOURCE_URL}
    username: ${USER_DATASOURCE_USERNAME}
    password: ${USER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: user_service
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: true
    out-of-order: false
    group: true
    mixed: false
    clean-disabled: false
    baseline-on-migrate: true
    fail-on-missing-locations: true
    placeholder-replacement: false
    sql-migration-suffixes: [ ".sql" ]

jwt:
  secret: ${JWT_SECRET}
  access-expire-time-ms: 86400000

eureka:
  client:
    enabled: false

logging:
  level:
    com.nowayback.user: DEBUG
    org.hibernate.SQL: DEBUG