auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki

  # 단일 인스턴스라서 복제 X 테스트 하면서 변경할게요,,
  replication_factor: 1

  storage:
    s3:
      bucketnames: ${S3_BUCKET_NAME}
      region: ap-northeast-2
      sse_encryption: true
      insecure: false

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: s3://ap-northeast-2/${S3_BUCKET_NAME}
    region: ap-northeast-2
    sse_encryption: true

  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: s3

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory   # 단일 인스턴스
      replication_factor: 1

  chunk_idle_period: 30m
  chunk_retain_period: 15m
  max_chunk_age: 2h
  chunk_encoding: snappy

distributor:
  ring:
    kvstore:
      store: inmemory

querier:
  max_concurrent: 10
  query_ingesters_within: 2h

frontend:
  max_outstanding_per_tenant: 1024
  compress_responses: true

limits_config:
  ingestion_rate_mb: 25
  ingestion_burst_size_mb: 50
  max_query_length: 720h

  max_query_parallelism: 8
  max_chunks_per_query: 500000

  max_streams_per_user: 0
  max_global_streams_per_user: 20000

  reject_old_samples: true
  reject_old_samples_max_age: 168h

  allow_structured_metadata: true

compactor:
  working_directory: /tmp/loki-compactor
  shared_store: s3
  compaction_interval: 30m
  retention_enabled: false
