spring:
  cloud:
    gateway:
      server:
        webflux:
          httpserver:
            wiretap: true
          httpclient:
            wiretap: true
          forwarded:
            enabled: true

          default-filters:
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**,/auth/**

            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/user-service/v3/api-docs
              filters:
                - RewritePath=/user-service/v3/api-docs, /v3/api-docs

            - id: project-service
              uri: lb://project-service
              predicates:
                - Path=/projects/**, /project-drafts/**

            - id: project-service-docs
              uri: lb://project-service
              predicates:
                - Path=/project-service/v3/api-docs
              filters:
                - RewritePath=/project-service/v3/api-docs, /v3/api-docs

            - id: funding-service
              uri: lb://funding-service
              predicates:
                - Path=/fundings/**

            - id: funding-service-docs
              uri: lb://funding-service
              predicates:
                - Path=/funding-service/v3/api-docs
              filters:
                - RewritePath=/funding-service/v3/api-docs, /v3/api-docs

            - id: reward-service
              uri: lb://reward-service
              predicates:
                - Path=/rewards/**,/qrcodes/**

            - id: reward-service-docs
              uri: lb://reward-service
              predicates:
                - Path=/reward-service/v3/api-docs
              filters:
                - RewritePath=/reward-service/v3/api-docs, /v3/api-docs

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**

            - id: payment-service-docs
              uri: lb://payment-service
              predicates:
                - Path=/payment-service/v3/api-docs
              filters:
                - RewritePath=/payment-service/v3/api-docs, /v3/api-docs

          globalcors:
            corsConfigurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                exposed-headers: "*"
                allowCredentials: true
                max-age: 3600

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  management:
    endpoints:
      web:
        base-path: /actuator
    endpoint:
      health:
        show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Funding Service
        url: /funding-service/v3/api-docs
      - name: Reward Service
        url: /reward-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
      - name: Project Service
        url: /project-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:yH2Nf5Q9bV4mE1uU2Z+8HsWlQq7R3pOjfL5xB0kDcZ8=}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    com.nowayback.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG