global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "otel-collector-user"
    static_configs:
      - targets: ["otel-collector-user:8889"]

  - job_name: "otel-collector-funding"
    static_configs:
      - targets: ["otel-collector-funding:8889"]

  - job_name: "otel-collector-reward"
    static_configs:
      - targets: ["otel-collector-reward:8889"]

  - job_name: "otel-collector-payment"
    static_configs:
      - targets: ["otel-collector-payment:8889"]

  - job_name: "otel-collector-project"
    static_configs:
      - targets: ["otel-collector-project:8889"]
