server:
  port: 18083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/encore_db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: reward-service-group-test
    topic:
      reward-creation-result: reward-creation-result
      project-reward-creation: project-reward-creation
      funding-failed: funding-failed
      funding-refund: funding-refund
      funding-completed: funding-completed

logging:
  level:
    root: INFO
    com.nowayback.reward: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
