spring:
  datasource:
    url: ${REWARD_DATASOURCE_URL}
    username: ${REWARD_DATASOURCE_USERNAME}
    password: ${REWARD_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        default_schema: reward_service

  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: true
    out-of-order: false
    group: true
    mixed: false
    clean-disabled: false
    baseline-on-migrate: true
    fail-on-missing-locations: true
    placeholder-replacement: false
    sql-migration-suffixes: [".sql"]
    default-schema: reward_service
    schemas: [reward_service]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: reward-service-group
    producer:
      acks: all

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN
    com.nowayback.reward: WARN
    org.springframework.web: ERROR
    org.springframework.kafka: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR