services:
  funding-service:
    build:
      context: ..
      dockerfile: funding/Dockerfile
    container_name: funding-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "18082:18082"
    restart: unless-stopped