server:
  port: 18082

spring:
  datasource:
    url: ${USER_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/encore_db}
    username: ${USER_SPRING_DATASOURCE_USERNAME:user}
    password: ${USER_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: funding_service
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:funding-service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.nowayback.funding: DEBUG
    org.hibernate.SQL: DEBUG

feign:
  client:
    config:
      reward-service:
        url: ${REWARD_SERVICE_URL:http://localhost:8080}
        connectTimeout: 3000
        readTimeout: 5000

      payment-service:
        url: ${PAYMENT_SERVICE_URL:http://localhost:8080}
        connectTimeout: 3000
        readTimeout: 10000

      project-service:
        url: ${PROJECT_SERVICE_URL:http://localhost:8080}
        connectTimeout: 3000
        readTimeout: 5000