server:
  port: 18082
  tomcat:
    threads:
      max: 1000
      min-spare: 100
    accept-count: 200
    max-connections: 2000

spring:
  datasource:
    url: ${USER_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/encore_db}
    username: ${USER_SPRING_DATASOURCE_USERNAME:user}
    password: ${USER_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 40
      connection-timeout: 5000
      validation-timeout: 1000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: funding_service
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:funding-service}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.nowayback.funding: DEBUG
    org.hibernate.SQL: DEBUG

feign:
  client:
    config:
      reward-service:
        url: http://localhost:18083
        connectTimeout: 3000
        readTimeout: 5000

      payment-service:
        url: http://localhost:18084
        connectTimeout: 3000
        readTimeout: 10000
