global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "reward-service"
    static_configs:
      - targets: ["reward.monitoring.local:18083"]
    metrics_path: '/actuator/prometheus'

  - job_name: "project-service"
    static_configs:
      - targets: [ "project.monitoring.local:18085" ]
    metrics_path: '/actuator/prometheus'

  - job_name: "funding-service"
    static_configs:
      - targets: [ "funding.monitoring.local:18082" ]
    metrics_path: '/actuator/prometheus'

  - job_name: "payment-service"
    static_configs:
      - targets: [ "payment.monitoring.local:18084" ]
    metrics_path: '/actuator/prometheus'

  - job_name: "user-service"
    static_configs:
      - targets: [ "user.monitoring.local:18081" ]
    metrics_path: '/actuator/prometheus'