global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "reward-service"
    static_configs:
      - targets: ["host.docker.internal:18083"]
    metrics_path: '/actuator/prometheus'

  - job_name: "project-service"
    static_configs:
      - targets: [ "host.docker.internal:18085" ]
    metrics_path: '/actuator/prometheus'
