server:
  port: 18085

spring:
  datasource:
    url: ${USER_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/encore_db}
    username: ${USER_SPRING_DATASOURCE_USERNAME:user}
    password: ${USER_SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: project_service
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: project-service

logging:
  level:
    com.nowayback.project: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    groups-order: desc
  show-actuator: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true